const menu=[
    {
        id: 1,
        title: 'buttermilk pancakes',
        category: 'breakfast',
        price: 15.99,
        img: "https://media.istockphoto.com/photos/closeup-of-bruschetta-with-eggs-picture-id473148144?k=20&m=473148144&s=612x612&w=0&h=gZvuorZYR8K10HWozqI_kdSHdPlIgalIlWaSQ0Pl6FU=", // img: './images/item-1.jpeg',
        desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
      },
      {
        id: 2,
        title: 'diner double',
        category: 'lunch',
        price: 13.99,
        img: "https://media.istockphoto.com/photos/double-burger-with-fries-and-sauce-on-wooden-board-picture-id1323804725?k=20&m=1323804725&s=612x612&w=0&h=SnEEWWn0lGh7wiZDEnVmi-pb_inRrK2ih1QO8JnJWck=",// img: './images/item-2.jpeg',
        desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
      },
      {
        id: 3,
        title: 'godzilla milkshake',
        category: 'dinner',
        price: 6.99,
        img: "https://media.istockphoto.com/photos/milk-shakes-in-plastic-cups-and-straws-on-a-dark-wooden-table-picture-id1311373994?k=20&m=1311373994&s=612x612&w=0&h=c5ZBvX65lxngG3NA4-ohfNuShvK-MJ-YoiONfRiGMMs=",// img: './images/item-3.jpeg',
        desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
      },
      {
        id: 4,
        title: 'country delight',
        category: 'breakfast',
        price: 20.99,
        img: "https://images.unsplash.com/photo-1496042399014-dc73c4f2bde1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Y291bnRyeSUyMGRlbGlnaHR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",// img: './images/item-4.jpeg',
        desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
      },
      {
        id: 5,
        title: 'egg attack',
        category: 'lunch',
        price: 22.99,
        img: "https://images.unsplash.com/photo-1591189863430-ab87e120f312?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8ZWdnJTIwYXR0YWNrfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",// img: './images/item-5.jpeg',
        desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
      },
      {
        id: 6,
        title: 'oreo dream',
        category: 'dinner',
        price: 18.99,
        img: "https://media.istockphoto.com/photos/seasoning-medium-rare-steak-with-salt-grinder-cut-on-wooden-board-on-picture-id1308569354?b=1&k=20&m=1308569354&s=170667a&w=0&h=0DlLDTE2c0dlnz1yhOLr6A8dqGPCSGOLzkrVihvDa00=",// img: './images/item-6.jpeg',
        desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
      },
      {
        id: 7,
        title: 'bacon overflow',
        category: 'breakfast',
        price: 8.99,
        img: "https://media.istockphoto.com/photos/pizza-with-extra-sauces-and-empty-space-still-life-picture-id1270746582?b=1&k=20&m=1270746582&s=170667a&w=0&h=C3AMuqG8qUr2SwcZLCpncg19j6GaCeOSwkI2CehJnB0=",// img: './images/item-7.jpeg',
        desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
      },
      {
        id: 8,
        title: 'american classic',
        category: 'lunch',
        price: 12.99,
        img: "https://images.unsplash.com/photo-1608198093002-ad4e005484ec?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTB8fGJyZWFkfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",// img: './images/item-8.jpeg',
        desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
      },
      {
        id: 9,
        title: 'quarantine buddy',
        category: 'dinner',
        price: 16.99,
        img: "https://media.istockphoto.com/photos/fall-salad-with-kale-and-butternut-squash-picture-id1325150700?b=1&k=20&m=1325150700&s=170667a&w=0&h=JtAldU8AI0VplC2A8bpxa9BkWMMf1C6SWt3Q10iK1Oc=",// img: './images/item-9.jpeg',
        desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
      },
]
export default menu